CREATE TABLE IF NOT EXISTS `programmi_svolti_verifiche_digitali` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `id_programma_svolto` int(11) NOT NULL,
    `id_anno_scolastico` int(11) NOT NULL,
    `id_docente` int(11) NOT NULL,
    `drive_folder_id` varchar(255) NOT NULL,
    `drive_file_id` varchar(255) NOT NULL,
    `drive_web_view_link` text DEFAULT NULL,
    `original_name` varchar(255) NOT NULL,
    `stored_name` varchar(255) NOT NULL,
    `mime_type` varchar(120) DEFAULT NULL,
    `file_size` bigint(20) DEFAULT NULL,
    `uploaded_by_user_id` int(11) DEFAULT NULL,
    `uploaded_at` datetime NOT NULL,
    `deleted_by_user_id` int(11) DEFAULT NULL,
    `deleted_at` datetime DEFAULT NULL,
    `created_at` datetime NOT NULL,
    `updated_at` datetime NOT NULL,
    PRIMARY KEY (`id`),
    KEY `idx_psvd_programma` (`id_programma_svolto`),
    KEY `idx_psvd_docente` (`id_docente`),
    KEY `idx_psvd_anno` (`id_anno_scolastico`),
    KEY `idx_psvd_deleted` (`deleted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
