CREATE TABLE IF NOT EXISTS ticket_evento (
    id INT AUTO_INCREMENT PRIMARY KEY,
    anno_scolastico_id INT NOT NULL,
    titolo VARCHAR(255) NOT NULL,
    descrizione TEXT NULL,
    luogo VARCHAR(255) NULL,
    data_evento DATETIME NOT NULL,
    apertura_prenotazioni DATETIME NULL,
    chiusura_prenotazioni DATETIME NULL,
    max_posti_per_utente INT NOT NULL DEFAULT 1,
    max_posti_totali INT NULL,
    visibile_studenti TINYINT(1) NOT NULL DEFAULT 1,
    visibile_docenti TINYINT(1) NOT NULL DEFAULT 1,
    visibile_ata TINYINT(1) NOT NULL DEFAULT 1,
    stato VARCHAR(20) NOT NULL DEFAULT 'bozza',
    creato_da_utente_id INT NULL,
    aggiornato_da_utente_id INT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_ticket_evento_anno (anno_scolastico_id),
    INDEX idx_ticket_evento_stato (stato),
    INDEX idx_ticket_evento_data (data_evento)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS ticket_prenotazione (
    id INT AUTO_INCREMENT PRIMARY KEY,
    evento_id INT NOT NULL,
    anno_scolastico_id INT NOT NULL,
    utente_id INT NULL,
    ruolo VARCHAR(30) NOT NULL,
    riferimento_id INT NOT NULL,
    nominativo VARCHAR(255) NOT NULL,
    email VARCHAR(255) NULL,
    classe_label VARCHAR(100) NULL,
    numero_posti INT NOT NULL DEFAULT 1,
    note VARCHAR(1000) NULL,
    stato VARCHAR(20) NOT NULL DEFAULT 'attiva',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uniq_ticket_prenotazione_attiva (evento_id, ruolo, riferimento_id),
    INDEX idx_ticket_prenotazione_evento (evento_id),
    INDEX idx_ticket_prenotazione_anno (anno_scolastico_id),
    CONSTRAINT fk_ticket_prenotazione_evento FOREIGN KEY (evento_id) REFERENCES ticket_evento(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
